"""'table1.0'

Revision ID: 1f851fa6bfb7
Revises: 
Create Date: 2020-06-23 14:26:40.436292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1f851fa6bfb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workno', sa.Unicode(length=128), nullable=False),
    sa.Column('number', sa.Unicode(length=128), nullable=False),
    sa.Column('name', sa.Unicode(length=32), nullable=False),
    sa.Column('model', sa.Unicode(length=128), nullable=False),
    sa.Column('type', sa.Unicode(length=32), nullable=False),
    sa.Column('manufacturer', sa.Unicode(length=32), nullable=False),
    sa.Column('sap', sa.Unicode(length=64), nullable=False),
    sa.Column('fixed_assets_no', sa.Unicode(length=128), nullable=False),
    sa.Column('fixed_assets_name', sa.Unicode(length=32), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('area', sa.Unicode(length=32), nullable=False),
    sa.Column('into_time', sa.DateTime(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'center_id')
    )
    op.create_table('fault_repair',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_no', sa.Unicode(length=256), nullable=False),
    sa.Column('workshop_no', sa.Unicode(length=128), nullable=False),
    sa.Column('no', sa.Unicode(length=256), nullable=False),
    sa.Column('worker_no', sa.Unicode(length=128), nullable=False),
    sa.Column('name', sa.Unicode(length=32), nullable=False),
    sa.Column('reason', sa.Unicode(length=128), nullable=False),
    sa.Column('picture', sa.Unicode(length=128), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workno', sa.Unicode(length=128), nullable=False),
    sa.Column('number', sa.Unicode(length=128), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.Column('model', sa.Unicode(length=128), nullable=False),
    sa.Column('type', sa.Unicode(length=32), nullable=False),
    sa.Column('manufacturer', sa.Unicode(length=64), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'center_id')
    )
    op.create_table('fitting_into',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.Unicode(length=256), nullable=False),
    sa.Column('fitting_no', sa.Unicode(length=1024), nullable=False),
    sa.Column('fitting_number', sa.Unicode(length=256), nullable=False),
    sa.Column('status', sa.Unicode(length=8), nullable=True),
    sa.Column('worker', sa.Unicode(length=128), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitting_out',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.Unicode(length=256), nullable=False),
    sa.Column('fitting_no', sa.Unicode(length=1024), nullable=False),
    sa.Column('fitting_number', sa.Unicode(length=256), nullable=False),
    sa.Column('out_worker', sa.Unicode(length=128), nullable=False),
    sa.Column('use_worker', sa.Unicode(length=128), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructionsCenter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Unicode(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Unicode(length=128), nullable=False),
    sa.Column('whl', sa.Unicode(length=64), nullable=True),
    sa.Column('gzl', sa.Unicode(length=64), nullable=True),
    sa.Column('wxfyl', sa.Unicode(length=64), nullable=True),
    sa.Column('gztjl', sa.Unicode(length=64), nullable=True),
    sa.Column('wxwcl', sa.Unicode(length=64), nullable=True),
    sa.Column('qjsbl', sa.Unicode(length=64), nullable=True),
    sa.Column('count', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lubrication_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_no', sa.Unicode(length=256), nullable=False),
    sa.Column('plan_no', sa.Unicode(length=128), nullable=False),
    sa.Column('position', sa.Unicode(length=64), nullable=False),
    sa.Column('oils', sa.Unicode(length=32), nullable=False),
    sa.Column('way', sa.Unicode(length=32), nullable=False),
    sa.Column('changes_amount', sa.Unicode(length=32), nullable=False),
    sa.Column('oils_changes_period', sa.Unicode(length=32), nullable=False),
    sa.Column('add_amount', sa.Unicode(length=32), nullable=False),
    sa.Column('oils_add_period', sa.Unicode(length=32), nullable=False),
    sa.Column('department', sa.Unicode(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Unicode(length=128), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('total_time', sa.Unicode(length=64), nullable=True),
    sa.Column('stop_time', sa.Unicode(length=64), nullable=True),
    sa.Column('repair_time', sa.Unicode(length=64), nullable=True),
    sa.Column('stop_count', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderVerify',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.Unicode(length=256), nullable=False),
    sa.Column('name', sa.Unicode(length=32), nullable=False),
    sa.Column('verify_status', sa.Unicode(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_no', sa.Unicode(length=256), nullable=False),
    sa.Column('no', sa.Unicode(length=256), nullable=False),
    sa.Column('worker_no', sa.Unicode(length=128), nullable=False),
    sa.Column('type', sa.Unicode(length=32), nullable=True),
    sa.Column('status', sa.Unicode(length=32), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_no', sa.Unicode(length=256), nullable=False),
    sa.Column('plan_no', sa.Unicode(length=128), nullable=False),
    sa.Column('position', sa.Unicode(length=64), nullable=False),
    sa.Column('tools', sa.Unicode(length=64), nullable=False),
    sa.Column('material', sa.Unicode(length=64), nullable=False),
    sa.Column('plan', sa.Unicode(length=64), nullable=False),
    sa.Column('standard', sa.Unicode(length=32), nullable=False),
    sa.Column('period', sa.Unicode(length=32), nullable=False),
    sa.Column('department', sa.Unicode(length=32), nullable=False),
    sa.Column('type', sa.Unicode(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_no', sa.Unicode(length=256), nullable=False),
    sa.Column('no', sa.Unicode(length=256), nullable=False),
    sa.Column('worker_no', sa.Unicode(length=128), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=True),
    sa.Column('fault_reason', sa.Unicode(length=128), nullable=False),
    sa.Column('repair_material', sa.Unicode(length=128), nullable=False),
    sa.Column('repair_status', sa.Unicode(length=12), nullable=True),
    sa.Column('fault_rank', sa.Unicode(length=12), nullable=True),
    sa.Column('knowledge', sa.Unicode(length=256), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_no', sa.Unicode(length=256), nullable=False),
    sa.Column('workshop_no', sa.Unicode(length=128), nullable=False),
    sa.Column('no', sa.Unicode(length=256), nullable=False),
    sa.Column('work_no', sa.Unicode(length=64), nullable=False),
    sa.Column('work_group', sa.Unicode(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Unicode(length=64), nullable=False),
    sa.Column('use_count', sa.Unicode(length=64), nullable=True),
    sa.Column('stock_count', sa.Unicode(length=64), nullable=True),
    sa.Column('worker', sa.Unicode(length=128), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Unicode(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no', sa.Unicode(length=256), nullable=False),
    sa.Column('equipment_no', sa.Unicode(length=256), nullable=False),
    sa.Column('workshop_no', sa.Unicode(length=128), nullable=False),
    sa.Column('worker_no', sa.Unicode(length=128), nullable=False),
    sa.Column('name', sa.Unicode(length=32), nullable=False),
    sa.Column('status', sa.Unicode(length=32), nullable=True),
    sa.Column('type', sa.Unicode(length=32), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Unicode(length=32), nullable=False),
    sa.Column('detail', sa.Unicode(length=256), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['instructionsCenter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_no', sa.Unicode(length=256), nullable=False),
    sa.Column('no', sa.Unicode(length=256), nullable=False),
    sa.Column('worker_no', sa.Unicode(length=128), nullable=False),
    sa.Column('name', sa.Unicode(length=32), nullable=False),
    sa.Column('no_status', sa.Unicode(length=32), nullable=True),
    sa.Column('verify_status', sa.Unicode(length=32), nullable=True),
    sa.Column('remind_status', sa.Unicode(length=32), nullable=True),
    sa.Column('type', sa.Unicode(length=32), nullable=True),
    sa.Column('work_time', sa.DateTime(), nullable=True),
    sa.Column('found_time', sa.DateTime(), nullable=True),
    sa.Column('plan_no', sa.Unicode(length=128), nullable=False),
    sa.Column('verify_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['verify_id'], ['orderVerify.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('PageRoute')
    op.drop_table('User')
    op.drop_table('SysLog')
    op.drop_table('CreateTableSet')
    op.drop_table('ISFlag')
    op.drop_table('InputTypeTable')
    op.drop_table('FieldType')
    op.drop_table('FieldSet')
    op.drop_table('AuditTrace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditTrace',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Operation', sa.NVARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('DeitalMSG', sa.NVARCHAR(length=800), autoincrement=False, nullable=True),
    sa.Column('ReviseDate', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('TableName', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('User', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Other', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__AuditTra__3214EC2738F5293F')
    )
    op.create_table('FieldSet',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TableName', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('TitleName', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('FieldName', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Isedit', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Edittype', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Downtable', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Sortable', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Order', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Visible', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('length', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('type', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('comment', sa.NVARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('primarykey', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('autoincrement', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('nullable', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('width', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__FieldSet__3214EC273FE48697')
    )
    op.create_table('FieldType',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Type', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Description', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__FieldTyp__3214EC2729BE9E15')
    )
    op.create_table('InputTypeTable',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Type', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Title', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__InputTyp__3214EC27F3420614')
    )
    op.create_table('ISFlag',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Flag', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Description', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__ISFlag__3214EC27C2CB62BC')
    )
    op.create_table('CreateTableSet',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TableName', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('TableDescrip', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('ISFirstCheckBox', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('SingleSelect', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('IsAdd', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('IsUpdate', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('IsDelete', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('TableID', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__CreateTa__3214EC274B3E5271')
    )
    op.create_table('SysLog',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IP', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('ComputerName', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('UserName', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('OperationDate', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('OperationContent', sa.NVARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('OperationType', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__SysLog__3214EC2728A8C7A4')
    )
    op.create_table('User',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Password', sa.NVARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('WorkNumber', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('StationName', sa.NVARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('Status', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('OrganizationName', sa.NVARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('FactoryName', sa.NVARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('LastLoginTime', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('CreateTime', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Creater', sa.NVARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('IsLock', mssql.BIT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__User__3214EC2775869D44')
    )
    op.create_table('PageRoute',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('SetRoute', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('PageRouteName', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('Route', sa.NVARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__PageRout__3214EC27054EC6DA')
    )
    op.drop_table('plan')
    op.drop_table('instructions')
    op.drop_table('work_order')
    op.drop_table('stock')
    op.drop_table('scheduling')
    op.drop_table('repair_record')
    op.drop_table('repair_plan')
    op.drop_table('record')
    op.drop_table('orderVerify')
    op.drop_table('monitor')
    op.drop_table('lubrication_plan')
    op.drop_table('kpi')
    op.drop_table('instructionsCenter')
    op.drop_table('fitting_out')
    op.drop_table('fitting_into')
    op.drop_table('fitting')
    op.drop_table('fault_repair')
    op.drop_table('Equipment')
    # ### end Alembic commands ###
