"""'table'

Revision ID: 6f15ea4ebb98
Revises: 
Create Date: 2020-04-10 13:00:43.998899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f15ea4ebb98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('fullname', sa.String(length=128), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_created_time'), 'users', ['created_time'], unique=False)
    op.create_index(op.f('ix_users_fullname'), 'users', ['fullname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_fullname'), table_name='users')
    op.drop_index(op.f('ix_users_created_time'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
