"""'table1-2'

Revision ID: b2b3f15d0cd5
Revises: eeb842390936
Create Date: 2020-06-09 16:00:16.648609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b3f15d0cd5'
down_revision = 'eeb842390936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'workname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('workname', sa.NVARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
