"""'table1-1'

Revision ID: eeb842390936
Revises: 3099c67c7bd1
Create Date: 2020-06-09 15:59:06.506035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb842390936'
down_revision = '3099c67c7bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('workname', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'workname')
    # ### end Alembic commands ###
